### ISSUE TITLE
Rust machine learning group

### ISSUE THREAD

**Issue by bytesnake** [smartcorelib/smartcore#3]
I can't find your email address, so I'm opening an issue here. There is a (not yet official) machine learning group for Rust. We are also working on a project for classical machine learning algorithms, called [linfa](https://github.com/rust-ml/linfa). At the moment we are trying to implement the most popular algorithms, and find a common interface for the learning process. Would be awesome if you say hello and share your project here https://rust-ml.zulipchat.com/

**Comment by VolodymyrOrlov** [comment]
Glad to get in touch, @bytesnake ! I've seen linfa at http://www.arewelearningyet.com/. Looks like the project has a vibrant community and has been in development for a while. Do you plan a release any time soon?

I will definitely join https://rust-ml.zulipchat.com, thanks for the invite! 

I will close this issue if you don't mind, since it served its purpose.

**Comment by bytesnake** [comment]
not yet .. we hope that a release will be possible end of the year, but there is a lot of work necessary in polishing and documentation :sweat_smile: will close this and see you in the zulip!
